# in case of change of baseURL must update fonts source URL 
# of "themes/ricettario2/assets/scss/theme/_fonts.scss"
baseURL = "https://mmbros.github.io/ricette/"

buildDrafts = false

languageCode = "it"
defaultContentLanguage = "it"

title = "Ricettario della casa"

theme = "ricettario3"

pluralizeListTitles = false

paginate = 10

[params]

[params.html]

description = "Sito delle ricette della famiglia"

breadcrumbHome = "Ricette"


[taxonomies]
  tagsaaaa = "tags"
  # cousine = "cucina"

